### ISSUE TITLE
Setting disabled property to true removes label

### ISSUE THREAD

**Issue by imcdonald-d2l** [BrightspaceUI/htmleditor#271]
When setting `disabled` property to `true` it is removing the label above the editor. I don't believe this is expected behavior. Was able to work around this issue by adding my own `<label>` tag and adding the `label-hidden` property.

Note that the labels are removed when setting `this.readOnly` to `true`.

![readonly-removing-label](https://user-images.githubusercontent.com/64804046/123129474-f420e700-d419-11eb-821d-eade3ef1edae.gif)

**Comment by grant-cleary** [comment]
Mm, yes, I feel like this is unintended. Thanks for raising this!
