### ISSUE TITLE
Links opened in same frame don't provide a method to exit/go back

### ISSUE THREAD

**Issue by lweber-d2l** [BrightspaceUI/htmleditor#275]
Environment: Quad; site version 20.21.8.31033.  Chrome 91.0.4472.114
Description:
* The Continuous Professional Development tool is an FRA.
* In that tool, we have a dialog that uses htmleditor so users can answer questions related to personal development activities.
* Insert a quick link > URL and set to Open in Same Frame.
* Save.  Open the dialog again.  Click the link.  The link opens but there is no easy way to exit/go back; user must reload the page.
Example: 
![link-in-same-frame-no-easy-exit](https://user-images.githubusercontent.com/59580355/123298385-724abf80-d4e6-11eb-9505-212d691ba505.gif)

**Comment by grant-cleary** [comment]
I don't think this is an editor bug, per se. The link is just a link; we don't do anything special to it in the editor. Setting same frame just sets the link to have `target=_self`, which in this case is the parent iframe.

**Comment by lweber-d2l** [comment]
Ok, fair point.  We can close this issue if this would be better handled elsewhere.

**Comment by grant-cleary** [comment]
Yeah, I'm not entirely certain what the right solution is here; I'm not familiar enough with FRAs to have a good idea of how these sorts of things are typically handled.

**Comment by lweber-d2l** [comment]
Thanks.  I've opened a Rally ticket to have the team look at this on the FRA side.
[DE44173](https://rally1.rallydev.com/#/431372673576d/workviews/collection?Name=%5BD2L%5D%20CPD%20-%20HTML%20answers%20linking%20URLs%20in%20same%20frame%20-%20navigation%20issue&Priority=Low&Project=%2Fproject%2F431372673576&Requirement=%2Fhierarchicalrequirement%2F603047402184&Severity=Minor%20Problem&detail=%2Fdefect%2F602554035593&itemRef=%2Fhierarchicalrequirement%2F603047402184&iteration=u&parentRef=%2Fhierarchicalrequirement%2F603047402184&previousTokens=%2F431372673576d%2Fiterationstatus%3Fdetail%3D%252Fuserstory%252F603047402184&project=%2Fproject%2F431372673576&rankTo=BOTTOM&ref=%2Fhierarchicalrequirement%2F603047402184&relationship=defects&fdp=true?fdp=true): [D2L] CPD - HTML answers linking URLs in same frame - navigation issue

**Comment by lweber-d2l** [comment]
To be addressed on the FRA side.  Tracking ticket: [DE44173](https://rally1.rallydev.com/#/431372673576d/iterationstatus?Name=%5BD2L%5D%20CPD%20-%20HTML%20answers%20linking%20URLs%20in%20same%20frame%20-%20navigation%20issue&Priority=Low&Project=%2Fproject%2F431372673576&Requirement=%2Fhierarchicalrequirement%2F603047402184&Severity=Minor%20Problem&detail=%2Fdefect%2F602554035593&fdp=true&itemRef=%2Fhierarchicalrequirement%2F603047402184&iteration=u&parentRef=%2Fhierarchicalrequirement%2F603047402184&previousTokens=%2F431372673576d%2Fiterationstatus%3Fdetail%3D%252Fuserstory%252F603047402184&project=%2Fproject%2F431372673576&rankTo=BOTTOM&ref=%2Fhierarchicalrequirement%2F603047402184&relationship=defects&fdp=true?fdp=true): [D2L] CPD - HTML answers linking URLs in same frame - navigation issue
